In [1]:
import numpy as np 

In [2]:
one_dimensional_array = np.array([1.1,2.2,3.3,4.4])

In [3]:
print(one_dimensional_array)

[1.1 2.2 3.3 4.4]


In [4]:
two_dimensional_array = np.array([[1,2],[3,4],[5,6]])

In [5]:
print(two_dimensional_array)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
sequences_of_integers = np.arange(2,6)

In [7]:
print(sequences_of_integers)

[2 3 4 5]


In [8]:
random_integers_between_20_and_60 = np.random.randint(low=20, high=61, size=(10))

In [9]:
print(random_integers_between_20_and_60)

[40 42 35 22 21 36 41 47 29 46]


In [10]:
random_floats_between_0_and_1 = np.random.random([7])

In [11]:
print(random_floats_between_0_and_1)

[0.62591053 0.38263296 0.50423252 0.27169279 0.00311777 0.91029938
 0.32217599]


In [12]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0

In [13]:
print(random_floats_between_2_and_3)

[2.62591053 2.38263296 2.50423252 2.27169279 2.00311777 2.91029938
 2.32217599]


In [14]:
random_integers_between_60_and_180 = random_integers_between_20_and_60 * 3

In [15]:
print(random_integers_between_60_and_180)

[120 126 105  66  63 108 123 141  87 138]


In [16]:
#TASK 1-CREATE A LINEAR DATASET

In [17]:
feature = np.arange(6,21)

In [18]:
 label = (3 * feature) + 4

In [19]:
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [20]:
#TASK 2-ADD SOME NOISE to the DATASET

In [21]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-0.66326433 -0.52657516 -1.2365928  -1.07126106  0.21867083  0.70467595
 -0.76175633  0.9022773  -0.44831309  1.36171977  0.87535021 -1.17818394
 -0.45535504 -1.48480195  1.36150388]
[21.33673567 24.47342484 26.7634072  29.92873894 34.21867083 37.70467595
 39.23824367 43.9022773  45.55168691 50.36171977 52.87535021 53.82181606
 57.54464496 59.51519805 65.36150388]
